language: python
python:
  - "3.6"

# install dependencies
install:
  - "pip install -r test-requirements.txt"
  - "python setup.py install"

# run tests
script:
  - flake8

notifications:
    slack: openmined:vOUE1d9jSb6V7R1r6zrjRD4E
